title: "All About Product Development and Engineering"
name: "Kausi"
description: >-
  A professional blog where I share insights, ideas, and lessons learned.
url: "https://kausalyap.github.io"
baseurl: "" # keep this empty for user.github.io pages

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache

# Author settings
author:
  name: "Kausi"
  avatar: ""
  bio: "Engineer. Learner. Writer."
  location: "Michigan, US"
  email: ""
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/yourusername"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/yourprofile"


# Social sharing image (optional)
og_image: ""

# Navigation (edit to match your pages)
header_pages:
  - about.md

# Footer settings
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/yourusername"
    - label: "RSS"
      icon: "fas fa-rss"
      url: "/feed.xml"

# Optional: Analytics, Disqus, etc.
# google_analytics: UA-XXXXXXXX-X
# disqus:
#   shortname: your-disqus-name
